repos:
 - repo: https://github.com/pre-commit/mirrors-mypy
   rev: v0.910
   hooks:
    - id: mypy
      name: 'Python types analyzer'
      args: ['--check-untyped-defs', '--cache-dir=/dev/null', '.']
      language: python
      pass_filenames: false

 - repo: https://github.com/pre-commit/mirrors-isort
   rev: v5.9.3
   hooks:
    - id: isort

 - repo: https://github.com/ambv/black
   rev: '21.7b0'
   hooks:
    - id: black
      language_version: python3.9

 - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
   rev: v1.2.1
   hooks:
    - id: 'python-safety-dependencies-check'
      args: ['check', '-r', 'Pipefile']
      files: './Pipefile'

 - repo: https://gitlab.com/pycqa/flake8
   rev: 3.9.2
   hooks:
    - id: flake8
      additional_dependencies: [flake8-typing-imports==1.10.0]

 - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
   rev: v1.0.5
   hooks:
    - id: python-bandit-vulnerability-check
